---
apiVersion: kubevirt.io/v1alpha3
metadata:
  labels:
    special: vm-fedora-persist
  name: vm-fedora-persist
kind: VirtualMachine
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-fedora-persist
    spec:
      networks:
      - name: default
        pod: {}
      domain:
        devices:
          interfaces:
            - name: default
              masquerade: {}
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          - disk:
              bus: virtio
            name: cloudinitdisk
          rng: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 2048M 
      livenessProbe:
        initialDelaySeconds: 150
        periodSeconds: 20
        httpGet:
          port: 1500
        timeoutSeconds: 10
      readinessProbe:
        initialDelaySeconds: 120
        periodSeconds: 5
        httpGet:
          port: 1500
        timeoutSeconds: 3
      terminationGracePeriodSeconds: 0
      volumes:
        - dataVolume:
            name: datavolumedisk1-dv
          name: datavolumedisk1
        - cloudInitNoCloud:
            userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
            ssh_pwauth: True
            disable_root: false
            ssh_authorized_keys:
                - ssh-rsa  AAAAB3Nz...0bLEgbgyYQ==
            bootcmd:
              - setenforce 0
              - dnf install -y nmap-ncat
              - sh -c "/usr/bin/echo -e HTTP/1.1 200 OK\\\n\\\nHello World! from $(hostname) > /etc/helloworld"
              - systemd-run --unit=httpserver nc -klp 1500 -e '/usr/bin/cat /etc/helloworld'
          name: cloudinitdisk
  dataVolumeTemplates:
    - metadata:
        name: datavolumedisk1-dv
      spec:
        pvc:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
        source:
          registry: 
            url: docker://quay.io/kubevirt/fedora-cloud-container-disk-demo