apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-eth1-policy 
spec:
  nodeSelector:
    networking.config/bridgenabled: "true"
  desiredState:
    interfaces:
      - name: br1-trunk 
        type: linux-bridge 
        state: up 
        bridge: 
          port:
            - name: ens224 
