apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br1-10
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1-trunk
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "br1-10",
    "type": "cnv-bridge",
    "bridge": "br1-trunk",
    "vlan": 10
  }'
