apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br1-15
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "cnv-bridge-conf",
    "plugins": [
      {
        "type": "cnv-bridge",
        "bridge": "br1-trunk",
        "vlan": 15
      },
      {
        "type": "cnv-tuning"
      }
    ]
  }'
