apiVersion: v1
items:
- apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachine
  metadata:
    annotations:
      description: test import
    labels:
      app: testvmdk
      flavor.template.kubevirt.io/medium: "true"
      os.template.kubevirt.io/fedora32: "true"
    name: testvmdk
    namespace: demovms
  spec:
    running: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          kubevirt.io/domain: testvmdk
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk-0
            inputs:
            - bus: virtio
              name: tablet
              type: tablet
            interfaces:
            - masquerade: {}
              model: virtio
              name: nic-0
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.2.0
          resources:
            requests:
              memory: 4Gi
        evictionStrategy: LiveMigrate
        hostname: testvmdk
        networks:
        - name: nic-0
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: r3om-pi3c-u53j
              chpasswd:
                expire: false
          name: cloudinitdisk
        - name: disk-0
          persistentVolumeClaim:
            claimName: imported-vm-disk
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
